# Generated by Django 4.1.7 on 2023-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=250)),
            ],
        ),
    ]
