# Generated by Django 4.1.7 on 2023-04-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='explicacao',
            field=models.CharField(default='vazio', max_length=1000),
            preserve_default=False,
        ),
    ]
