# Generated by Django 4.1.7 on 2023-04-12 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_presposta_pergunta_presposta'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrespondido_em', models.DateTimeField(auto_now_add=True)),
                ('rpergunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.pergunta')),
                ('rpuzzle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.puzzle')),
                ('rusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
