# Generated by Django 4.1.7 on 2023-04-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='progress',
        ),
    ]
